apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fcvn4y9q4-nodejs 
  janus-idp.io/tekton: fcvn4y9q4-nodejs
  backstage.io/kubernetes-id: fcvn4y9q4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fcvn4y9q4-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  